### PR TITLE
Update package dependencies

### PR DESCRIPTION
**Pull request by ascariandrea**

### CODE REVIEW

**Comment by gabro** [comment]
Is it really necessary to require react 0.13?

**Comment by gabro** [comment]
same applies to braintree-web, why the stricter requirement?

**Comment by ascariandrea** [comment]
I have a **warning** with braintree-web module in webpack, so I tried to update the module to the latest version, but the warning didn't go away. This is just to refer this repo in the issue I would create for braintree-web.

**Comment by gabro** [comment]
what's the warning?

**Comment by ascariandrea** [comment]
WARNING in ./~/braintree-web/dist/braintree.js  
Critical dependencies:
2:423-430 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
@ ./~/braintree-web/dist/braintree.js 2:423-430

**Comment by gabro** [comment]
Oh that's because the package is distributed as pre-built instead of providing the single file.
The dependency is not really the issue here, you might want to search/ask about this in the braintree-web repo

**Comment by ascariandrea** [comment]
So for the warning this pr is kind of useless, do you want to merge to have updated dependencies or do I have to close it? :/

**Comment by gabro** [comment]
The `browserify` update is welcome
`react` should probably be a `peerDependency` anyway so I wouldn't bother.
`braintree-web` has already been updated in the main repo.

So you can go ahead with the browserify update, but please do it in the main repo.

**Pull request closed without merging**
